version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thoughts
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data
    restart: unless-stopped
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3333:3333"
    command: ['npm', 'start']
    depends_on: 
      - mongodb
      - redis
    restart: always

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  mysql_data:
    driver: local